<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="AlumniChat.aspx.cs" Inherits="WebAppH.AlumniChat" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
         <link href="css/bootstrap.css" rel="stylesheet" />

    <style type="text/css">
        .container {
            background-color: #99CCFF;
            border: thick solid #808080;
            padding: 20px;
            margin: 20px;
        }
    </style>
    <div class ="contianer">
        <h1>Wall Post</h1>
        <div class ="well">
            <div class ="col-log-6"><input type="text" class ="alert-info form-control" id="message" /></div>
            <div class ="col-log-6"><input type="button" class ="btn btn-primary" id="sendmessage" value="Send" /></div>
            <div>
                <input type="hidden" id="displayname" />
                <div class ="panel panel-body"><h3><b>Latest Posts</b></h3><br />
                <p id="discussion" style="background-color:rgba(248, 241, 241, 0.18);"></p>
            </div>
        </div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.3.1.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page. 
                $('#discussion').append('<p style="margin:5px;padding:15px;background:whitesmoke;width:250px;border-radius:1em;"><strong>' + encodedName
                    + '</strong>:<br/>&nbsp;&nbsp;&nbsp;&nbsp;' + encodedMsg + '</><br/>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.  
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                });
            });
        });
    </script>
            </div>
        </div>
</asp:Content>
