//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.Web;

namespace WebAppH
{

        public partial class Image
        {
            public int ImageID { get; set; }

            public string Title { get; set; }
            [DisplayName("Upload File")]

            public string ImagePath { get; set; }

            public HttpPostedFileBase Imagefile { get; set; }
        }
    }

