//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlumniConnectEntities1 : DbContext
    {
        public AlumniConnectEntities1()
            : base("name=AlumniConnectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlumniRegistration> AlumniRegistrations { get; set; }
        public virtual DbSet<tblrole> tblroles { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
